mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
#    url: jdbc:mysql://192.168.29.128:3306/crawlerDB
    url: jdbc:mysql://localhost:3306/crawlerDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 1443
  ssl:
    key-store: classpath:chinoukin.xyz.jks
    key-store-password: 7312p6tmhn
  http:
    port: 8080

logging:
  level:
    root: INFO
    com.wisea.controller: DEBUG

web:
  cors: true

#redirectUris: https://www.chinoukin.xyz/auth_code
redirectUris: /auth_code



















